version: '3'

# Define the services/containers to be run
services:
  client:
    build:
      ./angular-src
    image: 
      karimelsayad247/sprints-project-client:latest
    container_name:
      sprints-client
    ports:
      - "80:80"
    networks:
      - sprints


  server:
    environment:
      - MONGO_URI
      - NODE_ENV=production
      - PORT=8080
    build:
        ./
    image:
      karimelsayad247/sprints-project-server:latest
    container_name:
      sprints-server
    ports:
      - "8080:8080"
    networks: 
      - sprints


networks:
  sprints:
    driver: bridge
    ipam:
      driver: default
